# Generated by Django 5.2.12 on 2026-05-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title, e.g. Software Engineer', max_length=200)),
                ('company', models.CharField(help_text='Company name', max_length=200)),
                ('field', models.CharField(help_text='Industry/field, e.g. Healthcare', max_length=100)),
                ('description', models.TextField(help_text='Full job description')),
                ('skills', models.CharField(help_text='Comma-separated required skills, e.g. Python, SQL, Git', max_length=500)),
                ('chroma_id', models.CharField(blank=True, editable=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Listing',
                'verbose_name_plural': 'Job Listings',
                'ordering': ['field', 'title'],
            },
        ),
    ]
